name: Anonymize Commits

on:
  push:
    branches:
      - main  

jobs:
  anonymize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is needed for rebase

      - name: Set Git user identity
        run: |
          git config --global user.name "Anonymous"
          git config --global user.email "anon@users.noreply.github.com"

      - name: Rewrite commit author
        run: |
          git rebase --root --committer-date-is-author-date -x "
            git commit --amend --no-edit --author='Anonymous <anon@users.noreply.github.com>'
          " || echo 'No changes needed'

      - name: Verify if force push is needed
        run: |
          if ! git diff origin/main; then
            echo "No changes to push"
            exit 0
          fi
          
          echo "Changes detected, force pushing..."
          git push --force --quiet https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/EchoedWords/cubechaos.git main
