name: Anonymize Commits

on:
  push:
    branches:
      - main  

jobs:
  anonymize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is needed

      - name: Set Git user identity
        run: |
          git config --global user.name "Anonymous"
          git config --global user.email "anon@users.noreply.github.com"

      - name: Rewrite commit history
        run: |
          git filter-branch --env-filter '
            export GIT_AUTHOR_NAME="Anonymous"
            export GIT_AUTHOR_EMAIL="anon@users.noreply.github.com"
            export GIT_COMMITTER_NAME="Anonymous"
            export GIT_COMMITTER_EMAIL="anon@users.noreply.github.com"
          ' --tag-name-filter cat -- --all

      - name: Force push changes
        run: |
          git push --force --quiet https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/EchoedWords/cubechaos.git main
